config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#show'

  resources :home

  resources :shops do
    get "/items/random", to: "items#random"
   resources :items do
     get "new_sale", to: "items#new_sale"
     post "cancel_sale"
     get "sale_cancelled", to: "items#sale_cancelled"
     resources :charges
   end
   collection { post :import }
 end


 get "/test" => 'shops#test'

end

app/models/shop.rb
class Shop < ActiveRecord::Base
  belongs_to :user
  has_many :items
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  skip_after_action :verify_authorized, only: [:index, :show]


  def index
    @shops = Shop.all
  end


  def show
    @shop = Shop.find(params[:id])
    @items = @shop.items.all
    @random = @items.sample
  end


  def import
    file = params[:file]
    shop = Shop.find(params[:shop_id])

    CSV.foreach(file.path, headers: true) do |row|
      shop.items.create!(name: row["Item"], description: row["Description"], price: row["Price"])
    end

    redirect_to shop_path(shop)
  end


  def test
  end


  def new
    @shop = Shop.new
    @shop.user_id = current_user.id
  end


  def create
    @shop = Shop.new(approved_params)
    @shop.user_id = current_user.id
    if @shop.save
      flash[:notice] = "Success!"
      redirect_to @shop
    else
      render :new
    end
  end


  def edit
    @shop = Shop.find(params[:id])
    authorize @shop
  end


  def update
    @shops = Shop.all
    @shop = Shop.find(params[:id])
    authorize @shop
    if @shop.update(approved_params)
      flash[:notice] = "Success!"
      redirect_to shops_path
    else
      redirect_to shops_path
    end
  end


  def destroy
    @shop = Shop.find(params[:id])
    authorize @shop
    @shop.destroy
    redirect_to shops_path
  end



  private

  def approved_params
    params.require(:shop).permit(:name, :description, :location)
  end


end

app/helpers/shop_helper.rb
module ShopHelper
end

app/views/shops/_form.html.erb
<%= form_for @shop, :html => { :class => "form-horizontal shop" } do |f| %>

  <% if @shop.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@shop.errors.count, "error") %> prohibited this shop from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @shop.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-6">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-6">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                shops_path(@shop), :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/shops/_import_form.html.erb
<li><%= form_tag import_shops_path, multipart: true do %>
  <%= hidden_field_tag :shop_id, shop.id %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %></li>
  <% end %>
  <br>

app/views/shops/_stripe_button.html.erb
<%= form_tag shop_item_charges_path(shop.id,item.id) do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span><%= item.on_sale? ? 'Sale Price' : 'Amount' %>
        <%= item.on_sale? ? number_to_currency(item.sale_price) : number_to_currency(item.price) %></span>
    </label>
  </article>



  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= ENV['PUBLISHABLE_KEY'] %>"
    data-description=<%= item.name %>
    data-amount=<%= item.on_sale? ? item.stripe_sale_amount : item.stripe_amount  %>
    data-locale="auto">
  </script>


<% end %>

app/views/shops/edit.html.erb
<%- model_class = Shop -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/shops/index.html.erb
<br><br>
<% @shops.each do |shop| %>
<div class="col-lg-12">
  <div class="well sidebar-nav">
    <ul class="nav nav-list">
      <li><h3><%= link_to shop.name, shop_path(shop) %></h3></li>
      <li id="desc"><%= shop.description %></li>
      <li id="location"><%= shop.location %></li>
      <% if current_user %>
        <% if policy(shop).edit? %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_shop_path(shop), :class => 'btn btn-default btn-xs' %>
        <% end %>
        <% if policy(shop).destroy? %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              shop_path(shop),
              :method => :delete,
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-xs btn-danger' %>
          <% end %>
        <% end %>
    </ul>
  </div><!--/.well -->
</div><!--/span-->
<% end %>

<p style="padding-left:15px;">
    <%= link_to ('Open a New Shop'), new_shop_path(@shop), :class => 'btn btn-main' %>
</p>

app/views/shops/new.html.erb
<%- model_class = Shop -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/shops/show.html.erb
<h1><%= @shop.name %></h1>
<% if current_user %>
  <% if policy(@shop).update? %>
  <%= render partial: 'shops/import_form', locals: { shop: @shop } %>
  <% end %>
<% end %>

<% if @random %>
  <h3>Random Item:</h3>
  <div class="well">
    <ul class="list-unstyled">
      <%= image_tag @random.image.url(:thumb) %>
      <li><%=link_to @random.name, shop_item_path(@shop, @random.id) %></li>
      <li><%= @random.description %></li>
      <%= render partial: 'shops/stripe_button', locals: { item: @random, shop: @shop }%>
    </ul>
    <h3><%= link_to "Click here to be whisked away to another randomly-selected item!", shop_items_random_path(@shop) %></h3>
  </div>
<% end %>

<% if @items %>
  <h3>All Items:</h3>
    <% @items.each do |item| %>
      <div class="well">
        <ul class="list-unstyled">
          <%= image_tag item.image.url(:thumb) %>
          <li><%=link_to item.name, shop_item_path(@shop, item.id) %></li>
          <li><%= item.description %></li>
              <%= render partial: 'shops/stripe_button', locals: { item: item, shop: @shop }%>
        </ul>
      </div><!--/.well -->
<% end %>

<% if current_user %>
    <% if policy(@shop).update? %>
      <p style="padding-left:15px;">
      <%= link_to ('Add New Item'), new_shop_item_path(@shop), :class => 'btn btn-main' %>
      </p>
    <% end %>
  <% end %>

<% end %>