config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#show'

  resources :home

  resources :shops do
    get "/items/random", to: "items#random"
   resources :items do
     get "new_sale", to: "items#new_sale"
     post "cancel_sale"
     get "sale_cancelled", to: "items#sale_cancelled"
     resources :charges
   end
   collection { post :import }
 end


 get "/test" => 'shops#test'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :shop
  belongs_to :seller
  belongs_to :user
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/


  def stripe_amount
    price.to_f * 100
  end


  def stripe_sale_amount
    sale_price.to_f * 100
  end


  def on_sale?
    if sale_end > Time.now
      return true
    else
      return false
    end
  end


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  include ActionView::Helpers::NumberHelper


  def index
    @shop = Shop.find(params[:id])
    @items = @shop.items.all
  end

  def show
    @shop = Shop.find(params[:shop_id])
    @item = @shop.items.find(params[:id])
    @end_date = (@item.sale_start + @item.sale_length.days).strftime("%A, %B %e, %Y %l:%M %P %Z")
    stripe_total #new method in Application Controller; gives correct Stripe total
                #depending on whether item is on sale or not
  end

  def new
    @shop = Shop.find(params[:shop_id])
    authorize @shop
    @item = @shop.items.new
    authorize @item
    @item.user_id = current_user.id
  end

  def create
    @shop = Shop.find(params[:shop_id])
    @item = @shop.items.new(approved_params)
    @item.user_id = current_user.id
    authorize @item
    authorize @shop
    if @item.save
      flash[:notice] = "Success!"
      redirect_to shop_path(@shop)
    else
      render :new
    end
  end

  def edit
    @shop = Shop.find(params[:id])
    authorize @shop
    @items = @shop.items.all
    @item = @shop.items.find(params[:shop_id])
    authorize @item
  end

  def update
    @shop = Shop.find(params[:shop_id])
    @item = @shop.items.find(params[:id])
    authorize @item
    if @item.update(approved_params)
      flash[:notice] = "Success!"
      redirect_to shop_path(@shop)
    else
      redirect_to shop_item_path
    end
  end

  def destroy
    @shop = Shop.find(params[:id])
    @item = @shop.items.find(params[:shop_id])
    authorize @item
    @item.destroy
    redirect_to shop_path
  end

  #chooses random item from shop to display
  def random
    @shop = Shop.find(params[:shop_id])
    @random = @shop.items.all.sample
  end

  #displays form to let shop owner put an
  #item on sale for whatever amount and number of days
  def new_sale
    @shop = Shop.find(params[:shop_id])
    @item = @shop.items.find(params[:item_id])
    @item.sale_start = Time.now
    @item.sale_end = Time.now + @item.sale_length.days
    @sale_percents = [10, 25, 50, 75, 90]
    if @item.save
      flash[:notice] = "Success!"
    else
      render :new
    end
  end


  def cancel_sale
    @shop = Shop.find(params[:shop_id])
    @item = @shop.items.find(params[:item_id])
    @item.sale_end = Time.now
    @item.sale_price = @item.price
    if @item.save
      redirect_to shop_item_sale_cancelled_path
    else
      flash[:notice] = "Error!"
    end
  end


  def sale_cancelled
    @shop = Shop.find(params[:shop_id])
    @item = @shop.items.find(params[:item_id])
  end



  private

  def approved_params
    params.require(:item).permit(:name, :description, :price, :shop_id, :image,
      :sale_price, :sale_length)
  end


end

app/helpers/item_helper.rb
module ItemHelper
end

app/views/items/_form.html.erb
<%= form_for [@shop, @item], multipart: true, :html => { :class => "form-horizontal item" } do |f| %>

    <!--error rescue-->
  <% if @item.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>


  <!--photo selector-->
  <%= f.file_field :image %>

  <!--form for item-->
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-6">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-6">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>

  <div class="form-group">
    <%= f.label :price, :class => 'control-label col-lg-2' %>
    <div class="col-lg-6">
      <%= f.text_field :price, :class => 'form-control' %>
    </div>
    <%=f.error_span(:price) %>
  </div>

  <!--submit/cancel buttons for item form-->
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                shop_path(@shop), :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/items/_review_form.html.erb
<%# Conditionally set remote: true. Also, passing model name as data attribute %>
<% modal ||= false %>
<% remote = modal ? true : false %>
<%= form_for(@review, remote: remote, url: reviews_path, html: {role: :form, 'data-model' => 'review'}) do |f| %>

  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%# Added Bootstrap classes, and help-block container for error messages %>
  <div class="form-group">
    <%= f.label :review_text, class: 'control-label' %><br>
    <%= f.text_field :review_text, class: 'form-control' %>
    <span class="help-block"></span>
  </div>


  <%# Added Bootstrap classes %>
  <div class="actions">
    <%= f.submit 'Submit', class: 'btn btn-default' %>
  </div>

<% end %>

app/views/items/_sale.html.erb
<%= form_for [@shop, @item], multipart: true, :html => { :class => "form-horizontal item" } do |f| %>

    <!--error rescue-->
  <% if @item.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>


  <!--form for running sale-->
  <div class="form-group">
    <%= f.label :sale_price, 'Sale Price', :class => 'control-label col-lg-2' %>
    <div class="col-lg-6">
      <%= f.text_field :sale_price, :class => 'form-control' %>
    </div>
    <%= f.error_span(:sale_price) %>
  </div>

  <div class="form-group">
    <%= f.label :sale_length, 'Length of Sale (specify a number of days)', :class => 'control-label col-lg-2' %>
    <div class="col-lg-6">
      <%= f.text_field :sale_length, :class => 'form-control' %>
    </div>
    <%= f.error_span(:sale_length) %>
  </div>


<%= f.collection_select :sale_percent, @sale_percents, :to_s, :to_s %>





  <!--submit/cancel/cancel sale buttons for sale form-->
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                shop_path(@shop), :class => 'btn btn-default' %>
      <%= link_to ('Cancel Sale'), shop_item_cancel_sale_path(@shop, @item), :method => 'update', :class => 'btn btn-default btn-danger' %>

    </div>
  </div>

<% end %>

app/views/items/_table_row.html.erb
<tr>
  <td><%= item.name %></td>
  <td><%= item.review.first %></td>
  <td><%= link_to 'Show', @review %></td>
  <td><%= link_to 'Edit', edit_person_path(person) %></td>
  <td><%= link_to 'Destroy', @review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/items/edit.html.erb
<!--edit item info-->
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/items/new.html.erb
<!--create new item for shop with _form partial-->
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/items/new_sale.html.erb
  <!--run a sale by filling out _sale partial form-->
<%- model_class = Item -%>
<div class="page-header">
  <h1>Create Sale</h1>
</div>

<%= render :partial => 'sale' %>

app/views/items/random.erb
<!--page generates random item from shop-->
<h3>Here is your random item! A friendly suggestion if you cannot decide.</h3>
<div class="well">
  <ul class="list-unstyled">
    <%= image_tag @random.image.url(:thumb) %>
    <li><%=link_to @random.name, shop_item_path(@shop, @random.id) %></li>
    <li><%= @random.description %></li>
    <%= render partial: 'shops/stripe_button', locals: { item: @random, shop: @shop }%>
  </ul>
</div>

app/views/items/random.html.erb
<!--page generates random item from shop-->
<h3>Here is your random item! A friendly suggestion if you cannot decide. Refresh your browser for more!</h3>
<div class="well">
  <ul class="list-unstyled">
    <%= image_tag @random.image.url(:thumb) %>
    <li><%=link_to @random.name, shop_item_path(@shop, @random.id) %></li>
    <li><%= @random.description %></li>
    <%= render partial: 'shops/stripe_button', locals: { item: @random, shop: @shop }%>
  </ul>
</div>

app/views/items/sale_cancelled.html.erb
<%= @item.name %> is no longer on sale

<!--navigation button returns to item view-->
<p style="padding-left:15px;">
<%= link_to shop_item_path(@shop, @item), class: "btn btn-default btn-sm" do %>
  <span class="glyphicon glyphicon-arrow-left"></span> Return to Item
<% end %>
</p>

app/views/items/show.html.erb
<div class="col-lg-3">
  <div class="well sidebar-nav">
    <ul class="nav nav-list">

      <!--basic item info-->
      <%= image_tag @item.image.url(:medium) %>
      <li><%= @item.name %></li>
      <li><%= @item.description %></li>
      <% if @item.on_sale? %>
        <strike><li><%= "Original Price: " + number_to_currency(@item.price) %></li></strike>
        <li><%= "Now Only " + number_to_currency(@item.sale_price) %></li>
        <li><%= "Sale Ends #{@end_date}" %></li>
      <% else %>
        <li><%=  number_to_currency(@item.price) %></li>
      <% end %>


      <!--partial for Stripe 'Pay With Card' button (see
        ApplicationController#stripe_total for @amount) -->
      <li><script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= ENV['PUBLISHABLE_KEY'] %>"
          data-description=<%= @item.name %>
          data-amount=<%= @amount %>
          data-locale="auto">
        </script></li>


      <!--edit/delete item buttons-->
      <% if current_user %>
        <% if policy(@item).edit? %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
          edit_shop_item_path(@item, @shop), :class => 'btn btn-default btn-xs' %>
        <% end %>
        <% if policy(@item).destroy? %>
      <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
          shop_item_path(@item, @shop),
          :method => :delete,
          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
          :class => 'btn btn-xs btn-danger' %>
        <% end %>
      <% end %>


      <!--run a sale-->
    <% if current_user %>
      <% if policy(@item).edit? %>
        <% if @item.on_sale? %>
          <p><%= link_to "Edit Sale Info", shop_item_new_sale_path(@shop, @item) %></p>
        <% else %>
          <h3><%= link_to "Sell this item on clearance to get it flying off the shelves!", shop_item_new_sale_path(@shop, @item) %></h3>
        <% end %>
      <% end %>
    <% end %>

    </ul>
  </div><!--/.well -->
</div><!--/span-->



  <!--reviews-->
<div id="myDIV" class="header">
  <h2>Reviews</h2>
  <input type="text" id="myInput" placeholder="Tell us what you think!...">
  <span onclick="newElement()" class="addBtn">Add Review</span>
</div>

<ul id="myUL">

</ul>



  <!--navigation button returns to shop-->
<p style="padding-left:15px;">
  <%= link_to shop_path(@shop), class: "btn btn-default btn-sm" do %>
    <span class="glyphicon glyphicon-arrow-left"></span> Return to Shop
  <% end %>
</p>

app/views/items/show.js.erb
$('#people_table').append("<%= j render partial: 'table_row', locals: {review: @review } %>");
$('#new_review_modal').modal_success();